Repository 3ndG4me/AutoBlue-MS17-010, pull requests merged in 2020-10, with the labels that each got.

#17 README.md and mysmb.py are updated
  README.md
  mysmb.py
Labels: bug

#20 Upgrading code to support python3
  README.md
  eternalblue_exploit10.py
  eternalblue_exploit7.py
  eternalblue_exploit8.py
  mysmb.py
  requirements.txt
Labels: enhancement

#22 Corrections for byte literals, spacing, minor function change, and updated the examples.
  mysmb.py
  zzz_exploit.py
Labels: enhancement, good first issue
